# Generated by Django 5.2.4 on 2025-08-21 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ss_app", "0002_disease_csv_file_disease_deaths_per_year_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aichatlog",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddField(
            model_name="aichatlog",
            name="conversation_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="aichatlog",
            name="is_user_message",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="aichatlog",
            name="prediction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ss_app.prediction",
            ),
        ),
    ]
